###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world!",
  "user_id": "7209e6d9-2340-4150-aca5-0ff8b97a05ec"
}

###

POST http://localhost:8080/admin/reset

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": 123
}

###
