###

GET http://localhost:8080/api/chirps

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world!",
  "user_id": "f3a3bf85-b1a0-42a6-9c2a-6218c35dbdcb"
}

###

POST http://localhost:8080/admin/reset

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": 123
}

###
