###

POST http://localhost:8080/admin/reset

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": 123
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp a chirp "
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "a chirp"
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "a chirp with Kerfuffle kerfuffle, fornax FORNAX FORNAX! sharbert"
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    body": "a chirp"
}
